### PR TITLE
Fix incorrect derivative of function w.r.t. parameterized argument alpha

### PR DESCRIPTION
**Pull request by bentyeh**

### CODE REVIEW

**Comment by bentyeh** [comment]
^bumping this PR

**Comment by psturmfels** [comment]
Sorry about the delay on this pull request. I’ve had an unexpected health crisis has caused me to take the last several months off of work. It looks like I no longer have access to the repository. @colah can you merge this?

**Comment by bentyeh** [comment]
^re-bumping this PR @colah

**Comment by bentyeh** [comment]
Bumping this PR

**Comment by bentyeh** [comment]
Bumping this PR again @colah @psturmfels

**Comment by colah** [comment]
I've merged the PR, but note that Distill is [on indefinite hiatus](https://distill.pub/2021/distill-hiatus/). Articles are no longer rebuilt.

**Pull request merged**
